<?php
    echo "\t" . "\t" . "\t" . '<div class="lb_content_title center">' . gethostname() . ': ' . $_SERVER['SERVER_ADDR'] . '</div>' . PHP_EOL;
    echo '<div class="lb_content">' . PHP_EOL;
    echo '<table>' . PHP_EOL;
    echo '<tr>' . PHP_EOL;
    echo '<td>Hostname</td>' . PHP_EOL;
    echo '<td>' . gethostname() . '</td>' . PHP_EOL;
    echo '</tr>' . PHP_EOL;
    echo '<tr>' . PHP_EOL;
    echo '<td>IP address</td>' . PHP_EOL;
    echo '<td>' . $_SERVER['SERVER_ADDR'] . '</td>' . PHP_EOL;
    echo '</tr>' . PHP_EOL;
    echo '<tr>' . PHP_EOL;
    echo '<td>Operating System</td>' . PHP_EOL;
    echo '<td>' . php_uname('s') . ' ' . php_uname('v') . '</td>' . PHP_EOL;
    echo '</tr>' . PHP_EOL;
    echo '<tr>' . PHP_EOL;
    echo '<td>Motherboard (S/N)</td>' . PHP_EOL;
    echo '<td>' . null . '</td>' . PHP_EOL;
    echo '</tr>' . PHP_EOL;
    echo '<tr>' . PHP_EOL;
    echo '<td>CPU</td>' . PHP_EOL;
    echo '<td>' . php_uname('m') . '</td>' . PHP_EOL;
    echo '</tr>' . PHP_EOL;
    echo '<tr>' . PHP_EOL;
    echo '<td>GPU</td>' . PHP_EOL;
    echo '<td>' . null . '</td>' . PHP_EOL;
    echo '</tr>' . PHP_EOL;
    echo '<td>RAM</td>' . PHP_EOL;
    echo '<td>' . null . '</td>' . PHP_EOL;
    echo '</tr>' . PHP_EOL;
    echo '<tr>' . PHP_EOL;
    echo '<td>System root</td>' . PHP_EOL;
    echo '<td>' . '/' . '</td>' . PHP_EOL;
    echo '</tr>' . PHP_EOL;
    echo '<tr>' . PHP_EOL;
    include("SOURCES/SCRIPTS/PHP/_get_freespace.php");
    echo '<td>Free disk space</td>' . PHP_EOL;
    echo '<td>' . number_format($disk_space_mb, 2) . ' GB/' . number_format($total_space_mb, 2) . " GB" . '</td>' . PHP_EOL;
    echo '</tr>' . PHP_EOL;
    echo '</table>' . PHP_EOL;
    echo '</div>' . PHP_EOL;
?>