server {
        listen 9292;
        server_name    lightbullet.ru;
        #change root here
        root  /ftpsd/SITE;

        index index.php;

        location /full {
                set $mobile_request 0;
                rewrite ^/full(.*)$ $1 break;
        }

        location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
                access_log off;
                expires max;
                log_not_found off;
        }

        #	error_page 403 /403.php;
        #	location /403.php {
        #		root /ftpsd/SITE;
        #		internal;
        #	}
        error_page 404 /404.php;
        error_page 500 502 503 504 /50x.php;

        location /testing {
                fastcgi_pass unix:/does/not/exist;
        }

        #change url here
        location / {
                try_files $uri $uri/ /index.php?$query_string;

                set $mobile_request 1;
                if ($http_referer ~* "http://(.*).lightbullet.ru/") {
                        set $mobile_request "0";
                }
                if ($http_user_agent ~* "(windows\smobile|windows\sce|iphone|ipod|midp|symbian|series\s60|s60|nokia|аndroid| blackberry|Android)"){
                        set $mobile_request "${mobile_request}1";
                }
                if ($mobile_request = 11) {
                        set $mobile_request "0";
                        return 302 http://m.lightbullet.ru/;
                }
        }

        location ~* \.php$ {
                try_files $uri = 404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }

        location ~ /\.ht {
                deny all;
        }
}
